# Generated by Django 4.0 on 2021-12-18 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_comment_created_at_like_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes_count',
        ),
    ]
